all:
	@echo ""
clean:
	cd cpython && make clean && cd ..
	cd cffi && make clean && cd ..
	cd boost && make clean && cd ..
	cd ctypes && make clean && cd ..
	cd pybind11 && make clean && cd ..
	cd swig && make clean && cd ..
	cd shiboken && make clean && cd ..
